# Generated by .github/workflows/release.yml — do not edit by hand.
class Agentjail < Formula
  desc "Policy guardrail for coding agents (Claude Code, Codex, Cursor)"
  homepage "https://agentjail.io"
  version "0.2.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.4/agentjail-v0.2.4-darwin-arm64.tar.gz"
      sha256 "9eb565f90f952f243de3808d1796d8ff8cbd82dd9ccc0682c4d2ecdc97c9e2a5"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.4/agentjail-v0.2.4-darwin-amd64.tar.gz"
      sha256 "a36fa14b0146de465de74c55939a277aeaa8eaf1a9e12a622240b0b38444aeea"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.4/agentjail-v0.2.4-linux-arm64.tar.gz"
      sha256 "e3be0718c33c15144d7be27a114b2a6116826e709e1c258c5e901573c33ae880"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.4/agentjail-v0.2.4-linux-amd64.tar.gz"
      sha256 "b602e674c05237e50a7f40a6e151407af760fd480ba62a2ac0cebefcf0c28924"
    end
  end

  def install
    bin.install "agentjail", "agentjail-hook", "agentjail-daemon",
                "agentjail-shield", "agentjail-netproxy"
  end

  def post_install
    ENV["AGENTJAIL_INSTALL_METHOD"] = "brew"
    system bin/"agentjail", "install", "--all"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentjail version")
  end
end
