# Generated by .github/workflows/release.yml — do not edit by hand.
class Agentjail < Formula
  desc "Policy guardrail for coding agents (Claude Code, Codex, Cursor)"
  homepage "https://agentjail.io"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.5/agentjail-v0.2.5-darwin-arm64.tar.gz"
      sha256 "d97c229ace8a32431cc810536746f112795828058b4577df1f6e9803b8e6f5e1"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.5/agentjail-v0.2.5-darwin-amd64.tar.gz"
      sha256 "dcdfc4baec92f41a0f462f52b6e170ac6abac82608109453c9cceb9510045d1f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.5/agentjail-v0.2.5-linux-arm64.tar.gz"
      sha256 "75518c69500306fcd8bf3054b2d1d2fae3b4ebf0a164d79dfeffc8dbc32e61da"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.2.5/agentjail-v0.2.5-linux-amd64.tar.gz"
      sha256 "70b8f1bf30f59e042c88295c204c1d36893b4199474527ceb0f2b91b5496d638"
    end
  end

  def install
    bin.install "agentjail", "agentjail-hook", "agentjail-daemon",
                "agentjail-shield", "agentjail-netproxy"
  end

  def post_install
    ENV["AGENTJAIL_INSTALL_METHOD"] = "brew"
    system bin/"agentjail", "install", "--all"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentjail version")
  end
end
