# Generated by .github/workflows/release.yml — do not edit by hand.
class Agentjail < Formula
  desc "Policy guardrail for coding agents (Claude Code, Codex, Cursor)"
  homepage "https://agentjail.io"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.1.0/agentjail-v0.1.0-darwin-arm64.tar.gz"
      sha256 "b9f55ff297b9866db6cf1c796241ad88a579341dc7b33188e43aae08515325e1"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.1.0/agentjail-v0.1.0-darwin-amd64.tar.gz"
      sha256 "3a92464ddfb6a59013236009e6b23ca14a8523c361950557f7b5dc0bd9b796f6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.1.0/agentjail-v0.1.0-linux-arm64.tar.gz"
      sha256 "40dbc1ecd2a4c672b53a32f047c20edfb2bf39dfa4be25dd9ff3a0e79dcea5d3"
    end
    on_intel do
      url "https://github.com/LuD1161/agentjail/releases/download/v0.1.0/agentjail-v0.1.0-linux-amd64.tar.gz"
      sha256 "14b4a48f14a21f921c9f34d8e7c856d96af2003f68be043bb5910973e72cdcbc"
    end
  end

  def install
    bin.install "agentjail", "agentjail-hook", "agentjail-daemon",
                "agentjail-shield", "agentjail-netproxy"
  end

  def post_install
    system bin/"agentjail", "install", "--all"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentjail version")
  end
end
